swagger: "2.0"
info:
  title: Stubber API
  version: 1.0.0
produces:
  - application/json
paths:
  /stub/all:
    get:
      summary: Получить все заглушки
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              sucess:
                type: boolean
              stubs:
                type: array
                items:
                  $ref: "#/definitions/Stub"
        "default":
          description: Fail
          schema:
            type: object
            properties:
              sucess:
                type: boolean

  /stub/{stubPath}:
    get:
      summary: Получить определенную заглушку
      parameters:
        - name: stubPath
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              sucess:
                type: string
              stub:
                $ref: "#/definitions/Stub"
        "default":
          description: Fail
          schema:
            type: object
            properties:
              sucess:
                type: boolean
  /stub/{stubPath}/start:
    get:
      summary: Запустить заглушку
      parameters:
        - name: stubPath
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Successful response
          schema:
            $ref: "#/definitions/Stub"
        "default":
          description: Fail
          schema:
            type: object
            properties:
              sucess:
                type: boolean
  /stub/{stubPath}/stop:
    get:
      summary: Остановить заглушку
      parameters:
        - name: stubPath
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Successful response
          schema:
            $ref: "#/definitions/Stub"
        "default":
          description: Fail
          schema:
            type: object
            properties:
              sucess:
                type: boolean

definitions:
  Stub:
    type: object
    properties:
      jar:
        type: string
        example: credits_stub_b1.jar
      path:
        type: string
        example: /usr/WF/stubs/credits_stub_b1.jar
      state:
        type: boolean
      pid:
        type: string
        example: 77178
      port:
        type: string
        example: 8080
      cpu:
        type: string
        example: 10.1
      mem:
        type: string
        example: 1.2
