// Package stubber_service provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package gen_service

// Stub defines model for Stub.
type Stub struct {
	Jar   *string `json:"jar,omitempty"`
	Path  string  `json:"path"`
	State *bool   `json:"state,omitempty"`
	Pid   *string `json:"pid,omitempty"`
	Cpu   *string `json:"cpu,omitempty"`
	Mem   *string `json:"mem,omitempty"`
	Port  *string `json:"port,omitempty"`
}

// PostStubJSONRequestBody defines body for PostStub for application/json ContentType.
type PostStubJSONRequestBody = Stub

// PostStubStartJSONRequestBody defines body for PostStubStart for application/json ContentType.
type PostStubStartJSONRequestBody = Stub

// PostStubStopJSONRequestBody defines body for PostStubStop for application/json ContentType.
type PostStubStopJSONRequestBody = Stub
