/*
 * Stubber API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {

	Sucess bool `json:"sucess,omitempty"`

	Stub *Stub `json:"stub,omitempty"`
}
